<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PublishAot>true</PublishAot>
        <SelfContained>true</SelfContained>
        <PublishDir>$(MLOutDir)</PublishDir>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <NoWarn>LNK4099</NoWarn>
        <InvariantGlobalization>true</InvariantGlobalization>
        <DebugType>portable</DebugType>
    </PropertyGroup>
    
    <PropertyGroup Condition="'$(RuntimeIdentifier.StartsWith(`linux-`))' == 'true'">
        <ExportsFile>linuxexports.def</ExportsFile>
        <StripSymbols>false</StripSymbols>
        <LinuxEntryPath>Deps/$(RuntimeIdentifier)/linuxentry.o</LinuxEntryPath>
        <LinuxPltHookPath>Deps/$(RuntimeIdentifier)/plthook.o</LinuxPltHookPath>
    </PropertyGroup>

    <ItemGroup Condition="'$(RuntimeIdentifier.StartsWith(`win-`))' == 'true'">
        <LinkerArg Include="/DEF:Exports.def" />
    </ItemGroup>

    <ItemGroup Condition="'$(RuntimeIdentifier.StartsWith(`linux-`))' == 'true'">
        <LinkerArg Include="-lstdc++" />
    </ItemGroup>

    <PropertyGroup Condition="'$(Configuration)' != 'Debug'">
        <DebugSymbols>false</DebugSymbols>
        <DebugType>none</DebugType>
    </PropertyGroup>

    <ItemGroup>
        <None Include="../BaseLibs/NetStandardPatches/*" CopyToOutputDirectory="PreserveNewest" Link="MelonLoader/Dependencies/NetStandardPatches/%(RecursiveDir)%(Filename)%(Extension)" />
        <None Include="$(SolutionDir)/NOTICE.txt" CopyToOutputDirectory="PreserveNewest" Link="MelonLoader/Documentation/%(Filename)%(Extension)" />
        <None Include="$(SolutionDir)/LICENSE.md" CopyToOutputDirectory="PreserveNewest" Link="MelonLoader/Documentation/%(Filename)%(Extension)" />
        <None Include="$(SolutionDir)/CHANGELOG.md" CopyToOutputDirectory="PreserveNewest" Link="MelonLoader/Documentation/%(Filename)%(Extension)" />
        <None Include="$(SolutionDir)/README.md" CopyToOutputDirectory="PreserveNewest" Link="MelonLoader/Documentation/%(Filename)%(Extension)" />
    </ItemGroup>
    
    <ItemGroup>
        <EmbeddedResource Include="TrimmerRoots.xml">
            <LogicalName>ILLink.Descriptors.xml</LogicalName>
        </EmbeddedResource>
    </ItemGroup>

    <PropertyGroup>
        <AppHostVersion>9.0.0</AppHostVersion>
        <AppHostPath>$(NuGetPackageRoot)runtime.$(RuntimeIdentifier).microsoft.netcore.dotnetapphost/$(AppHostVersion)/runtimes/$(RuntimeIdentifier)/native/libnethost$(LibExt)</AppHostPath>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NETCore.DotNetAppHost" Version="$(AppHostVersion)" PrivateAssets="All" />
        <PackageReference Include="Pastel" Version="6.0.1" />
        <PackageReference Include="Samboy063.Tomlet" Version="6.0.0" />
    </ItemGroup>
    
    <ItemGroup>
        <Compile Include="$(SolutionDir)/MelonLoader/LoaderConfig.cs" />
    </ItemGroup>

    <ItemGroup>
        <NativeLibrary Include="$(AppHostPath)" />
<!--        <None Include="Deps/$(RuntimeIdentifier)/$(LibPrefix)dobby$(LibExt)" Link="$(LibPrefix)dobby$(LibExt)" CopyToOutputDirectory="Always" />-->
    </ItemGroup>

    <ItemGroup Condition="'$(RuntimeIdentifier.StartsWith(`linux-`))' == 'true'">
        <NativeLibrary Include="$(LinuxEntryPath)" />
        <NativeLibrary Include="$(LinuxPltHookPath)" />
    </ItemGroup>

    <ItemGroup>
      <ClCompile Include="LinuxEntry\LinuxEntry.cpp" />
      <ClCompile Include="LinuxEntry\plthook\plthook_elf.c" />
    </ItemGroup>

    <Target Name="PublishAsBuildAfterTarget" AfterTargets="Build" DependsOnTargets="Publish" />
    
    <Target Condition="'$(RuntimeIdentifier.StartsWith(`linux-`))' == 'true'" Name="BuildLinuxEntry" BeforeTargets="Build">
        <Exec Command="g++ -g -c -O0 -fpermissive -fPIC LinuxEntry/LinuxEntry.cpp -o $(LinuxEntryPath)" />
        <Exec Command="g++ -g -c -O0 -fpermissive -fPIC LinuxEntry/plthook/plthook_elf.c  -o $(LinuxPltHookPath)"/>
    </Target>

    <Target Condition="'$(RuntimeIdentifier.StartsWith(`win-`))' == 'true'" Name="RenameBinary" AfterTargets="Build">
        <Move SourceFiles="$(PublishDir)/$(TargetName).dll" DestinationFiles="$(PublishDir)/version.dll" />
    </Target>

    <Target Condition="'$(RuntimeIdentifier.StartsWith(`win-`))' == 'false'" Name="CopyDobby" AfterTargets="Build">
        <Copy SourceFiles="Deps/$(RuntimeIdentifier)/$(LibPrefix)dobby.so" DestinationFiles="$(PublishDir)/$(LibPrefix)dobby.so" />
    </Target>
</Project>